#!/bin/sh                                                                                                                           
SCALA_VERSION=2.12.18 ALMOND_VERSION=0.14.0-RC14
curl -L -o coursier https://git.io/coursier-cli &&
    chmod +x coursier \
    && ./coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION -o almond \
    && ./almond --install \
    && rm almond coursier \
    && python -m sos_notebook.install \
    && rm apt.txt install.R requirements.txt runtime.txt postBuild
